# -*- coding: utf-8 -*-
"""Deep_Learning_with_Keras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M2DDc9hpiCceeZnD_NBhtqDPUyeDV2ST
"""

from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
layer1 = Dense(5, input_dim = 4)    # 5 -> no. of neurons
model.add(layer1)

layer2 = Dense(3, activation = 'relu')
model.add(layer2)

# The above code can be written this way
layer1 = Dense(5, input_dim = 4)
layer2 = Dense(3, activation = 'relu')
model = Sequential([layer1, layer2])

layer3 = Dense(1, activation = 'sigmoid')
layer4 = Dense(4, activation = 'softmax')
model.add(layer3)

# Model Configuration and Training
res = model.compile('adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
# train_output = model.fit(data, labels, batch_size = 20 , epochs(iterations) = 5)

# Model Execution and Evaluation
# model.evaluate(test_data, test_labels))

# Model Predictions
# model.predict(new_data)

